# Generated by Django 3.2.5 on 2021-07-28 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_order', models.IntegerField(verbose_name='題目序數')),
                ('date', models.DateTimeField(null=True, verbose_name='日期')),
                ('categories', models.CharField(choices=[('AC', 'AC'), ('NA', 'NA'), ('WA', 'WA'), ('TLE', 'TLE'), ('MLE', 'MLE'), ('OLE', 'OLE'), ('RE', 'RE'), ('RF', 'RF'), ('CE', 'CE'), ('SE', 'SE')], default='請選擇科目', max_length=10, verbose_name='科目')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
