# Generated by Django 3.2.5 on 2021-07-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='categories',
        ),
        migrations.AddField(
            model_name='problem',
            name='result',
            field=models.CharField(choices=[('AC', 'AC'), ('NA', 'NA'), ('WA', 'WA'), ('TLE', 'TLE'), ('MLE', 'MLE'), ('OLE', 'OLE'), ('RE', 'RE'), ('RF', 'RF'), ('CE', 'CE'), ('SE', 'SE')], default='請選擇科目', max_length=10, verbose_name='解題狀態'),
        ),
    ]
